### ISSUE TITLE
Issue adding and removing channels

### ISSUE THREAD

**Issue by caerffili** [Sekkmer/StarWindXExtLib#2] opened 2020-05-05 07:37 UTC
This is amazing work but I'm having problems understanding how to use it.

I'm trying to add and remove heartbeat channels but I'm getting exceptions

`-
control 0x0000015EEFAE14C0 -ChannelType:"heartbeat" -IP:"10.20.30.43" -PartnerTargetName:"iqn.2008-08.com.starwindsoftware:starwind2.glass.caerffili.co.uk-partnerha22" -Port:"3260" -action:"remove"
-`

It doesn't appear to be putting AddRemovePartnerInterface parameter in. Here is a section of my code-

```
foreach (IHAPartnerExt partner in ha.PartnersExt)
{
  Console.WriteLine("        Partner " + partner.TargetName);
                                
  foreach (IHANetworkInterface chan in partner.SynchronizationChannels)
  {
    Console.WriteLine("            " + chan.InterfaceType + " " + chan.IPAddress + "    " + chan.Port + "    " + chan.PartnerId);
  }

  foreach (IHANetworkInterface chan in partner.HeartbeatChannels)
  {
    Console.WriteLine("            " + chan.InterfaceType + " " + chan.IPAddress + "    " + chan.Port + "    " + chan.PartnerId);

  if (Console.ReadKey().Key == ConsoleKey.D )
  {
    ServerControl RemovePartner = (ServerControl)ha.RemovePartnerInterface(chan);
    starWindXComponent.Control(RemovePartner);
  }
}
```

I can enumerate through the partners and channels fine but the remove fails wit the above exception.

It's likely to be something I'm doing wrong so it would be great if you could advise please or provide a little example.

Good work by the way.

**Comment by Sekkmer** [comment] 2020-05-08 03:26
Your code seems alright for me, so I will make a test see what the problem is, possibly something changed the way StarWind handle this request since this was not tested for some time now, sadly StarWind does not give good reasons why something went wrong, the exception barely contains the string representation of the request sent to the server, I will try to schedule the test during the next week

**Comment by caerffili** [comment] 2020-05-08 09:55
I think I might have found a fix or workaround. In ParameterAppender.cs starting on line 69, I've added an entry for ParamValueAsNameAttribute

```
          foreach (var info in properties)
            {
                if (!info.CanRead) continue;
                if (info.GetCustomAttribute<ParamAttribute>(true) is { } attr)
                {
                    if (IsEnabled(attr) && ToString(info, info.GetValue(obj)) is { } str)
                    {
                        pars.AppendParam(prefix + attr.Name, str);
                    }
                }
                else if (info.GetCustomAttribute<ParamValueAsNameAttribute>(true) is { } attr2)
                {
                    if (IsEnabled(attr2) && ToString(info, info.GetValue(obj)) is { } str)
                    {
                        pars.AppendParam(prefix + str, "");
                    }
                }
                else if (info.GetCustomAttribute<FlatParamAttribute>(true) is { } flat)
                {
                    if (IsEnabled(flat)) Append(pars, info.GetValue(obj), flat.Prefix);
                }
                else if (info.GetCustomAttribute<SubParamAttribute>(true) is { } sub)
                {
                    if (!IsEnabled(sub)) continue;
                    var newPars = pars.AppendParams(sub.Name);
                    Append(newPars, info.GetValue(obj), sub.Prefix);
                }
            }
```

I don't know if the fix is valid, but it seems to fix the problem for me.

**Comment by Sekkmer** [comment] 2020-05-08 17:05
Yes this should not be missing from there, thanks, I added this as a quick fix, I close this for now and run tests on it as I have time

https://github.com/Sekkmer/StarWindXExtLib/commit/434a4c595e694de98cf660424614bd7881591160

**Closed as completed by Sekkmer** 2020-05-08 17:05 UTC
Labels: bug
